CRUD/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('first_app.urls'))
]

first_app/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views

app_name='first_app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="home"),
    path('student', views.student, name="student"),
    path('student_info/<int:student_id>',views.student_info, name="student_info"),
    path('info_edit/<int:student_id>/', views.info_edit, name="info_edit"),
    path('student_delete/<int:student_id>', views.delete, name="delete"),
  
]

first_app/models.py
from django.db import models

# Create your models here.
class StudentForm(models.Model):
    first_name=models.CharField(max_length=250)
    last_name=models.CharField(max_length=250)
    email=models.EmailField()
    phone=models.IntegerField()

    def __str__(self):
        return str(self.pk)+" "+ self.first_name
    

first_app/forms.py
from django import forms
from first_app import models

class Student(forms.ModelForm):
    class Meta:
        model= models.StudentForm
        fields="__all__"

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app import forms
from first_app.models import StudentForm

# Create your views here.
def index(request):
    main_form=forms.Student()
    dictionary={'form_here':main_form, 'title':"Index"}
    if request.method=="POST":
        main_form=forms.Student(request.POST)

        if main_form.is_valid():
            main_form.save(commit=True)



    return render (request,"first_app/index.html",context=dictionary)

def student(request):
    all_students= StudentForm.objects.all()
    diction={'title':"Students", 'students':all_students}

    return render(request,"first_app/students.html", context=diction)

def student_info(request,student_id):
    student_info=StudentForm.objects.get(pk=student_id)
    diction={'student_info':student_info}
    return render (request,"first_app/students_info.html", context=diction )

def info_edit(request,student_id):

    student_data=StudentForm.objects.get(pk=student_id)

    student_form=forms.Student(instance=student_data)
    diction={'student':student_form}

    if request.method=="POST":
        student_form=forms.Student(request.POST,instance=student_data)
        if student_form.is_valid():
            student_form.save(commit=True)
            
    return render (request,"first_app/info_edit.html",context=diction)

def delete(request,student_id):
    student_delete=StudentForm.objects.get(pk=student_id).delete()
    return render(request,"first_app/delete.html")

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <div class=" container-fluid ">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'first_app:home' %}">CRUD</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'first_app:home' %}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'first_app:student' %}">Students</a>
            </li>
           
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </div>

      {% block home_content %}

      {% endblock %}




</body>
</html>

templates/first_app/delete.html
{% extends 'first_app/base.html' %}

{% block home_content %}
<h2 class="alert alert-danger">Deleted Successfully</h2>
{% endblock %}

templates/first_app/index.html
{% extends 'first_app/base.html' %}

{% block home_content %}
<div class="container-fluid">
<h2>Enter Students Data:</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form_here}}
    <input type="submit" value="SUBMIT">
</form>
</div>
{% endblock %}

templates/first_app/info_edit.html
{% extends 'first_app/base.html' %}

{% block home_content %}
<div class="container-fluid">
<form action="" method="POST">
    {% csrf_token %}
    {{student.as_p}}
    <input type="submit" value="SUBMIT">

</form>
</div>
{% endblock %}

templates/first_app/students.html
{% extends 'first_app/base.html' %}

{% block home_content %}

<div class="container-fluid">

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            {% for student in students %}
            <tr>
                <td scope="row">{{student.id}}</td>
                <td>{{student.first_name}}</td>
                <td>{{student.last_name}}</td>
                <td>{{student.email}}</td>
                <td>{{student.phone}}</td>
                <td> 
                    <a type="button" class="btn btn-primary" href="{% url 'first_app:student_info' student_id=student.id %}" >View</a>
                    <a type="button" class="btn btn-success" href="{% url 'first_app:info_edit' student_id=student.id %}" >Edit</a>
                    <a type="button" class="btn btn-danger" href="{% url 'first_app:delete' student_id=student.id%}" >Delete</a>
                
                </td>
            </tr>

            {% endfor %}
           
        </tbody>
    </table>

</div>

{% endblock %}

templates/first_app/students_info.html
{% extends 'first_app/base.html' %}

{% block home_content %}
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone No</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td scope="row">{{student_info.id}}</td>
            <td>{{student_info.first_name}}</td>
            <td>{{student_info.last_name}}</td>
            <td>{{student_info.email}}</td>
            <td>{{student_info.phone}}</td>
        </tr>
       
    </tbody>
</table>
{% endblock home_content %}